name: 有 BUG ?! ⚠
description: 模板中的错误反馈
title: "[错误]："
labels: ["error"]
body:
  - type: markdown
    attributes:
      value: 感谢小伙伴的反馈，请填写该表格描述你遇到的错误内容
  - type: dropdown
    id: Series
    attributes:
      label: 版本系列
      description: 请问出现的错误存在于哪个版本系列呢？
      options:
        - Miki Stickie.V1
        - Miki Stickie.V2
        - Miki Stickie.V3
        - Miki Stickie.V4
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 版本号
      description: 请问发生错误的具体版本号是（可填全部）？
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: 类型
      description: 请问该错误是哪个类型？
      options:
        - 文件无法打开
        - 文件兼容性问题
        - 色彩搭配禁忌
        - 错别字（本人常病）
        - 元素丢失（无法加载）
        - 效果无法呈现
        - 其他
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 错误类型中没有你遇到的问题？
      description: 如果在类型列表中没有你遇到的问题，请选择其他并在此处手动填写
      placeholder: 请在此处填入你认为该错误的类型，这将帮助咱修改 Miki Home for Github 的提问表单
    validations:
      required: false
  - type: textarea
    id: error-message
    attributes:
      label: 发生什么事了？
      description: 请问此版本存在的错误内容是？
      placeholder: 会根据严重性决定是否在本版本更改，如果并非必要的将避免在新版本中出现
    validations:
      required: true
  - type: textarea
    id: solutions
    attributes:
      label: 啊，这样啊，那你能帮我么？
      description: 请问对于该问题你有什么好的解决方案呢？（**除开错别字**）
      placeholder: 如果你愿意，可以写出你的修复方案，咱将在版本更新的时候将你的名字添加入贡献者名单
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: 如果你愿意，可以在此留下联系方式哦~
    validations:
      required: false
  - type: checkboxes
    id: attention 
    attributes:
      label: 提交前须知
      description: |
            请注意，如果你愿意提供联系方式（包含昵称），我们会将你列入贡献者列表中。
            如果联系方式未填写，将视为不愿意透露姓名，为保证你的隐私将在贡献者列表中计入 “热心的小伙伴” 群体名单中
      options:
        - label: 我同意以上内容，并已经根据此规则重新考虑过是否选择匿名
          required: true
  - type: checkboxes
    id: rules
    attributes:
      label: 行为准则
      description: 为了保证此社区的质量，请你遵循此社区行为准则 [Miki Home Rules](https://github.com/MikiLin-wiviw/Miki-Stickie/blob/master/documents/Miki-Home-Rules.md) 的内容
      options:
        - label: 我同意遵守 **Miki Home Rules**
          required: true
  - type: checkboxes
    id: license
    attributes:
      label: 本项目库模板遵循 CC BY-NC-SA 4.0 许可协议
      description: 本社区的模板采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 许可协议
      options:
        - label: 我同意遵守 **CC BY-NC-SA 4.0** 协议内容
          required: true
